.TH SWANNSONGADV 6 2020-10-04 "SwannSong Adventure"
.SH NAME
swannsongadv \- A text-adventure game with some humor
.SH SYNOPSIS
.B swannsongadv
[\fB\-\-local\fR]
[\fB\-\-debug\fR]
[\fB\-\-reset\fR]
.SH OPTIONS
.TP
.B --local
use the game data from the current directory (this is mainly useful for running the program in its build directory without installing it).
.TP
.B --debug
enable debug features such as warning logs (mainly for developers).
.TP
.B --reset
remove the game user configuration as if it was a fresh install.
